name: 'HEXO CI'

## 監聽 main 分支若有 push 行為就執行
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-detph: 0
    - name: Set time zone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Taipei"
        timezoneMacos: "Asia/Taipei"
        timezoneWindows: "Taipei Standard Time"
    # 恢復檔案修改時間
    - name: Restore file modification time
      run: |
        find source/_posts -name '*.md' | while read file; do touch -d "$(git log -1 --pretty="@%ct" -- $file)" $file; done
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: init)init ssh
      run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.HEXO_DEPLOY_PRI}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "Connand"
          git config --global user.email "babbab0114@gmail.com"
    - name: A)npm install
      run: |
        npm install
    - name: B)npm install -g hexo-cli
      run: |
        npm install -g hexo-cli
    - name: C) hexo d -g
      run: |
        git clone https://github.com/Connand/Connand.github.io public
        hexo d -g
